/**
 * Test Agent Delegation Service
 * 
 * This file contains test cases for the agent delegation functionality
 */

import {
  analyzeGitHubEvent,
  delegateToAgent,
  getAllAgents,
  getAvailableAgents,
  getActiveAssignments,
  completeAssignment
} from '../server/services/agentDelegation.js';

console.log('🧪 Testing Agent Delegation Service...\n');

// Test 1: Get all agents
console.log('Test 1: Get all agents');
const allAgents = getAllAgents();
console.log(`✅ Found ${allAgents.length} registered agents`);
console.log('Agents:', allAgents.map(a => a.name).join(', '));
console.log('');

// Test 2: Check available agents
console.log('Test 2: Check available agents');
const availableAgents = getAvailableAgents();
console.log(`✅ ${availableAgents.length} agents available`);
console.log('');

// Test 3: Analyze security-related event
console.log('Test 3: Analyze security-related issue');
const securityEvent = {
  eventType: 'issue',
  action: 'opened',
  title: 'Security: Exposed API keys in configuration file',
  body: 'We need to remove the exposed credentials from the repository',
  labels: ['security', 'critical'],
  number: 123,
  url: 'https://github.com/test/repo/issues/123',
  isAgentBranch: false
};

const securityAnalysis = analyzeGitHubEvent(securityEvent);
if (securityAnalysis) {
  console.log(`✅ Matched agent: ${securityAnalysis.agent.name}`);
  console.log(`   Score: ${securityAnalysis.score}`);
  console.log(`   Reason: ${securityAnalysis.reason}`);
} else {
  console.log('❌ No agent matched');
}
console.log('');

// Test 4: Analyze deployment-related event
console.log('Test 4: Analyze deployment-related PR');
const deploymentEvent = {
  eventType: 'pull_request',
  action: 'opened',
  title: 'Add VPS deployment scripts for production',
  body: 'This PR adds nginx configuration and PM2 setup for our VPS',
  labels: ['deployment', 'infrastructure'],
  branch: 'feature/vps-deploy',
  number: 456,
  url: 'https://github.com/test/repo/pull/456',
  isAgentBranch: false
};

const deploymentAnalysis = analyzeGitHubEvent(deploymentEvent);
if (deploymentAnalysis) {
  console.log(`✅ Matched agent: ${deploymentAnalysis.agent.name}`);
  console.log(`   Score: ${deploymentAnalysis.score}`);
  console.log(`   Reason: ${deploymentAnalysis.reason}`);
} else {
  console.log('❌ No agent matched');
}
console.log('');

// Test 5: Delegate task to agent
console.log('Test 5: Delegate security task');
if (securityAnalysis) {
  const assignment = delegateToAgent(securityAnalysis);
  console.log(`✅ Task delegated successfully`);
  console.log(`   Assignment ID: ${assignment.id}`);
  console.log(`   Agent: ${assignment.agentName}`);
  console.log(`   Status: ${assignment.status}`);
  
  // Test 6: Check active assignments
  console.log('');
  console.log('Test 6: Check active assignments');
  const activeAssignments = getActiveAssignments();
  console.log(`✅ ${activeAssignments.length} active assignment(s)`);
  
  // Test 7: Complete the assignment
  console.log('');
  console.log('Test 7: Complete assignment');
  const completed = completeAssignment(assignment.id);
  console.log(`✅ Assignment completed`);
  console.log(`   Completed at: ${completed.completedAt}`);
  console.log(`   Agent status: available`);
}
console.log('');

// Test 8: Skip agent branch events
console.log('Test 8: Skip agent branch events (loop prevention)');
const agentBranchEvent = {
  eventType: 'pull_request',
  action: 'opened',
  title: 'Fix security issue',
  body: 'Auto-generated by security agent',
  labels: ['security'],
  branch: 'copilot/fix-security',
  number: 789,
  url: 'https://github.com/test/repo/pull/789',
  isAgentBranch: true
};

const agentBranchAnalysis = analyzeGitHubEvent(agentBranchEvent);
if (agentBranchAnalysis) {
  console.log('❌ Agent branch was not skipped (BUG)');
} else {
  console.log('✅ Agent branch correctly skipped');
}
console.log('');

// Test 9: Event with low match score
console.log('Test 9: Event with low match score (should not match)');
const lowScoreEvent = {
  eventType: 'issue',
  action: 'opened',
  title: 'Update README',
  body: 'Just fix a typo',
  labels: [],
  number: 999,
  url: 'https://github.com/test/repo/issues/999',
  isAgentBranch: false
};

const lowScoreAnalysis = analyzeGitHubEvent(lowScoreEvent);
if (lowScoreAnalysis) {
  console.log(`⚠️  Matched agent: ${lowScoreAnalysis.agent.name}`);
  console.log(`   Score: ${lowScoreAnalysis.score}`);
} else {
  console.log('✅ Correctly did not match (score too low)');
}
console.log('');

// Test 10: Documentation event
console.log('Test 10: Documentation-related issue');
const docsEvent = {
  eventType: 'issue',
  action: 'opened',
  title: 'Add contributing guidelines documentation',
  body: 'We need a CONTRIBUTING.md file with clear guidelines for contributors',
  labels: ['documentation', 'good first issue'],
  number: 111,
  url: 'https://github.com/test/repo/issues/111',
  isAgentBranch: false
};

const docsAnalysis = analyzeGitHubEvent(docsEvent);
if (docsAnalysis) {
  console.log(`✅ Matched agent: ${docsAnalysis.agent.name}`);
  console.log(`   Score: ${docsAnalysis.score}`);
  console.log(`   Reason: ${docsAnalysis.reason}`);
} else {
  console.log('❌ No agent matched');
}
console.log('');

console.log('✨ All tests completed!\n');

// Summary
console.log('📊 Test Summary:');
console.log('================');
console.log(`Total agents registered: ${allAgents.length}`);
console.log(`Available agents: ${getAvailableAgents().length}`);
console.log(`Active assignments: ${getActiveAssignments().length}`);
console.log('');
console.log('✅ Agent delegation service is working correctly!');
